apiVersion: v1
kind: Service
metadata:
  name: easy-roles
  namespace: default
  labels:
    app: easy-roles
spec:
  type: ClusterIP
  ports:
  - port: 8082
  selector:
    app: easy-roles
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-roles
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: easy-roles
  template:
    metadata:
      labels:
        app: easy-roles
    spec:
      containers:
        - name: easy-roles
          image: gcr.io/rock-solid-robots/easy-roles:1c9ae8ad-a2a4-4ff9-bfff-06a7eed1faa7
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: "/"
              port: 8082
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/"
              port: 8082
            initialDelaySeconds: 10
            timeoutSeconds: 5
          env:
            - name: PORT
              value: "8082"
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: easy-roles
                  key: discord-token
                  optional: false
            - name: DISCORD_ID
              valueFrom:
                secretKeyRef:
                  name: easy-roles
                  key: discord-id
                  optional: false
            - name: DISCORD_PUBKEY
              valueFrom:
                secretKeyRef:
                  name: easy-roles
                  key: discord-pubkey
                  optional: false
            - name: REDIS_URI
              valueFrom:
                secretKeyRef:
                  name: easy-roles
                  key: redis-uri
                  optional: false
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: easy-roles
                  key: mongo-uri
                  optional: false
        - name: easy-roles-gateway
          image: gcr.io/rock-solid-robots/easy-roles-gateway:cee90740-d5c3-4c90-a7d8-b3bc594e0f1e
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: easy-roles
                  key: discord-token
                  optional: false
            - name: TARGET_URI
              value: "http://easy-roles:8082/member-join"
        - name: easy-roles-redis
          image: redis:latest
          ports:
          - containerPort: 6379
