apiVersion: v1
kind: Service
metadata:
  name: easy-roles-redis
  namespace: default
  labels:
    app: easy-roles-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: easy-roles-redis
---
apiVersion: v1
kind: Pod
metadata:
  name: easy-roles-redis
  namespace: default
  labels:
    app: easy-roles-redis
spec:
  containers:
  - name: easy-roles-redis
    image: redis:latest
    ports:
    - containerPort: 6379